services:
  monkeysphere:
    build:
      context: .
    ports:
      - "5080:8080"
    environment:
      MONKEYSPHERE_ADMIN_USERNAME: "${MONKEYSPHERE_ADMIN_USERNAME:-admin}"
      MONKEYSPHERE_ADMIN_PASSWORD: "${MONKEYSPHERE_ADMIN_PASSWORD:-admin}"
      DnaX__RemoteAccess__Enabled: "false"
    volumes:
      - monkeysphere-data:/data
    restart: unless-stopped

volumes:
  monkeysphere-data:
