<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Monkeysphere.Core/Monkeysphere.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="DnaX.Data.Migrations" />
    <PackageReference Include="DnaX.Data.Migrations.Sqlite" />
    <PackageReference Include="DnaX.Hosting" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>

</Project>
