using System.IO.Compression;
using System.Text.Json;
using Dapper;
using Microsoft.Data.Sqlite;
using Monkeysphere.Data;

namespace Monkeysphere.Web.Tests;

// Format 1 packages are single-domain archives that the current code can no longer produce.
// The fixture was generated by the last format 1 commit (30e8bea) and is committed unchanged,
// so this exercises the real compatibility path rather than a package the current writer made.
//
// These tests deliberately stop at the restored data root and inspect it with SQL. Booting the
// application against it currently fails: the fixture's migration ledger was written before
// commit 4eddd54 stabilized checksums across line endings, so DnaX reports the database as
// 'Drifted' and refuses to migrate. That defect is recorded in docs/roadmap.md under the
// migration ledger compatibility item; asserting it here would enshrine the broken behavior.
public sealed class ArchivedBackupCompatibilityTests
{
    private static string FixturePath => Path.Combine(AppContext.BaseDirectory, "Fixtures", "format-1-schema-18.monkeysphere-backup");

    [Fact]
    public void ArchivedFixtureIsAGenuineSingleDomainFormatOnePackage()
    {
        using ZipArchive archive = ZipFile.OpenRead(FixturePath);
        string[] paths = archive.Entries.Select(entry => entry.FullName).ToArray();
        Assert.Contains("manifest.json", paths);
        Assert.Contains("databases/monkeysphere.db", paths);
        Assert.Contains("databases/remote-access.db", paths);
        Assert.Single(paths, path => path.EndsWith(".original.png", StringComparison.Ordinal));
        Assert.DoesNotContain(paths, path => path.StartsWith("domains/", StringComparison.Ordinal));

        using Stream manifestStream = archive.GetEntry("manifest.json")!.Open();
        using JsonDocument manifest = JsonDocument.Parse(manifestStream);
        Assert.Equal(1, manifest.RootElement.GetProperty("formatVersion").GetInt32());
        // Format 1 predates the domain catalogue entirely.
        Assert.False(manifest.RootElement.TryGetProperty("domains", out _));
        int schema = manifest.RootElement.GetProperty("applicationSchemaVersion").GetInt32();
        Assert.Equal(18, schema);
        Assert.True(schema < MonkeysphereSchema.Manifest.CurrentVersion,
            "The fixture must stay older than the current schema so the upgrade path stays meaningful.");
    }

    [Fact]
    public async Task ArchivedFormatOnePackageRestoresItsLegacyLayoutAndContent()
    {
        string dataRoot = Path.Combine(Path.GetTempPath(), "Monkeysphere.Tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dataRoot);
        try
        {
            SqliteConnection.ClearAllPools();
            string rollback = await OfflineBackupRestore.RestoreAsync(FixturePath, dataRoot);
            Assert.True(Directory.Exists(rollback));

            // Format 1 restores to the legacy single-database layout, with no domain directories.
            string database = Path.Combine(dataRoot, "monkeysphere.db");
            Assert.True(File.Exists(database));
            Assert.True(File.Exists(Path.Combine(dataRoot, "remote-access.db")));
            Assert.False(Directory.Exists(Path.Combine(dataRoot, "domains")));

            // The retained original image is restored; regenerable derivatives are deliberately absent.
            string[] media = Directory.Exists(Path.Combine(dataRoot, "media", "records"))
                ? Directory.GetFiles(Path.Combine(dataRoot, "media", "records"), "*", SearchOption.AllDirectories)
                : [];
            Assert.Single(media, path => path.EndsWith(".original.png", StringComparison.Ordinal));
            Assert.DoesNotContain(media, path => path.Contains("preview", StringComparison.OrdinalIgnoreCase));

            SqliteConnectionStringBuilder connectionString = new() { DataSource = database, Mode = SqliteOpenMode.ReadOnly };
            await using SqliteConnection connection = new(connectionString.ConnectionString);
            await connection.OpenAsync();
            Assert.Equal("ok", await connection.ExecuteScalarAsync<string>("PRAGMA integrity_check;"));
            Assert.Equal("Format one contact", await connection.ExecuteScalarAsync<string>("SELECT DisplayName FROM Records;"));
            Assert.Equal("Legacy alias", await connection.ExecuteScalarAsync<string>("SELECT Value FROM RecordAliases;"));
            Assert.Equal("Recorded before deployment-wide backups.",
                await connection.ExecuteScalarAsync<string>("SELECT TextValue FROM FieldValues;"));
            Assert.Equal(1, await connection.ExecuteScalarAsync<int>("SELECT COUNT(*) FROM RecordImages;"));
        }
        finally
        {
            SqliteConnection.ClearAllPools();
            await TestDataRoot.DeleteWhenReleasedAsync(dataRoot);
        }
    }
}
